/*******************************************************
 *         MVSilicon Audio Effects Parameters          *
 *   The File is Auto Generated by ACPWorkbench V6.9   *
 *              Firmware Version: 6.8                  *
 *                All Right Reserved                   *
 *******************************************************/

#ifndef __AUDIO_EFFECT_H__
#define __AUDIO_EFFECT_H__

#ifdef  __cplusplus
extern "C" {
#endif//__cplusplus

#define AUDIO_EFFECT_VERSION_DRC               (010307)
#define AUDIO_EFFECT_VERSION_VB                (030400)
#define AUDIO_EFFECT_VERSION_3D                (030200)
#define AUDIO_EFFECT_VERSION_PS                (010503)
#define AUDIO_EFFECT_VERSION_ECHO              (010000)
#define AUDIO_EFFECT_VERSION_REVERB            ()

#define AUDIO_EFFECT_PARAM_DRC_THRESHHOLD      (-0)
#define AUDIO_EFFECT_PARAM_DRC_RATIO           (1)
#define AUDIO_EFFECT_PARAM_DRC_ATTACK_TIME     (10)
#define AUDIO_EFFECT_PARAM_DRC_RELEASE_TIME    (60)
#define AUDIO_EFFECT_PARAM_DRC_CROSSOVER_FREQ  (0)
#define AUDIO_EFFECT_PARAM_VB_CUTOFF_FREQ      (100)
#define AUDIO_EFFECT_PARAM_VB_LIMITER_EN       (1)
#define AUDIO_EFFECT_PARAM_VB_INTENSITY        (35)
#define AUDIO_EFFECT_PARAM_VB_PREGAIN          (32768)
#define AUDIO_EFFECT_PARAM_VB_POSTGAIN         (32768)
#define AUDIO_EFFECT_PARAM_3D_DEPTH            (50)
#define AUDIO_EFFECT_PARAM_3D_PREGAIN          (32768)
#define AUDIO_EFFECT_PARAM_3D_POSTGAIN         (32768)
#define AUDIO_EFFECT_PARAM_PS_SEMITONE_STEP    (0)
#define AUDIO_EFFECT_PARAM_PS_FRAME_SIZE       (576)
#define AUDIO_EFFECT_PARAM_ECHO_DELAY          (8820)
#define AUDIO_EFFECT_PARAM_ECHO_ATTENUATION    (11626)
#define AUDIO_EFFECT_PARAM_REVERB_DRY_SCALE    (50)
#define AUDIO_EFFECT_PARAM_REVERB_WET_SCALE    (100)
#define AUDIO_EFFECT_PARAM_REVERB_WIDTH_SCALE  (100)
#define AUDIO_EFFECT_PARAM_REVERB_ROOM_SIZE    (50)
#define AUDIO_EFFECT_PARAM_REVERB_DAMPING      (50)

#ifdef  __cplusplus
}
#endif//__cplusplus

#endif//__AUDIO_EFFECT_H__
